src/layout/forceDirected.ts
This seems to work and doesn't seem to be breaking anything else?
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Use `forceX` and `forceY` instead of `forceCenter`

src/symbols/Arrow.tsx
Before:
After:
- Prevents the gap, but I'm not convinced it's the best solution (maybe the line should extend into the arrow instead?)
=> Set `DoubleSide` on the arrow heads

docs/Theme.story.mdx, src/symbols/Edge.tsx, src/symbols/Node.tsx, src/utils/themes.ts
```
[ ] Bugfix
[x] Feature
```
Use the theme to set a custom opacity
We cannot change the opacity
We can change the opacity
```
[ ] Yes
[x] No
```
=> Use theme to define opacity

src/selection/utils.ts
It throws an error everytime a node is not connected to something, which I don't think should happen.
=> bugfix: Safe graph links iteration

src/GraphScene.tsx, src/store.ts, src/symbols/Edge.tsx, src/symbols/Node.tsx, src/useGraph.ts, src/utils/buildGraph.ts, src/utils/collapse.ts
```
[ ] Bugfix
[x] Feature
```
Nodes/edges are hidden from the graph but are only hidden visually. Since they are still part of the graph, they are taken into account with zoom/node locations
Maintain an internal/external graph and node/edge state. The internal state will house what is being rendered on the graph while the external state maintains the full list of passed in nodes/edges. These states allow the graph to determine links between hidden …
=> maintain internal graph state for hidden nodes/edges

src/GraphScene.tsx, src/store.ts, src/symbols/Edge.tsx, src/symbols/Node.tsx, src/types.ts, src/useGraph.ts, src/utils/buildGraph.ts, src/utils/collapse.ts
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Currently a graph's initial state containing all nodes and edges is maintained within the store
Issue Number: https://linear.app/goodcodeus/issue/QAI-1/graph-collapse-refactor
Within useGraph, use the passed nodes and edges along with the store's collapsedNodeIds list to determine a list of visible nodes and edges. Use these to build and update the graph layout
```
[x] Yes
[ ] No
```
It's technically a breaking change for collapsible …
=> Collapsible refactor

src/GraphScene.tsx, src/symbols/edges/Edge.tsx, src/symbols/edges/Edges.tsx
```
[x] Bugfix
[ ] Feature
```
Custom font is not used on edges when animated is false
Issue Number: #120
Custom font is used on edges when animated is false
```
[ ] Yes
[x] No
```
=> fix issue edge custom font not working when animated is false

docs/assets/demo.ts, src/layout/forceDirected.ts, src/utils/cluster.ts
This PR fixes the boundary overlap issue in clusters.
```
[x] Bugfix
[ ] Feature
```
Boundaries overlap when there are a large number of nodes.
Example: 100 nodes in 4 clusters
There is no overlap when there are large number of nodes and clusters.
Example: 100 nodes in 4 clusters
Example: 100 nodes in 7 clusters
Example: 500 nodes in 4 clusters
Example: 500 nodes in 7 clusters
```
[ ] Yes
[x] No
```
=> Added heuristics for cluster boundary spacing

docs/demos/Basic.story.tsx, src/GraphScene.tsx, src/symbols/Node.tsx
Adding ability to handle double click event on `<Node/>`.
Use case I was trying to cover, if for example we have Team object as `<Node/>` and when user double clicks on it, I want to get more nodes (as hierarchy inside the team) and re-render the graph.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Add doubleClick to <Node/>

src/CameraControls/CameraControls.tsx
Looks like a bug.
When use keys(up,down,left,right) to move canvas it works fine, but when click on button in UI to move canvas (up,down,left,right) visually it doesn't show any movements, but in real it's very tiny unnoticeable movement.
This PR fixes the issue.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Allow passing deltaTime to CameraControl movements

docs/demos/Basic.story.tsx, src/GraphCanvas.tsx
After some internet search, found that to make ability to save/download Canvas as a picture extra configuration should be passed to `gl` attribute as `preserveDrawingBuffer: true`. To avoid hardcoded value, decided to make it as configurable parameter on user level.
```js
// If canvas is created like this:
<GraphCanvas glOptions={{ preserveDrawingBuffer: true }}/>
// the following pseudo-code should work
const url = getControls()._domElement?.toDataURL();
const fakeDownloader = document.createElement('a');
fakeDownloader.href = url;
fakeDownloader.download = 'canvas';
fakeDownloader.click();
fakeDownloader.remove();
```
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, …
```
=> Add glOptions to GraphCanvas to extend gl configutation

src/symbols/Cluster.tsx
```
[x] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
[x] Build related changes
```
*Literally this is first time I contribute in github and pardon my english*
I am modifying a line of code where if labelFontUrl is signed, label on cluster didn't work just like node label, it still show squareboxes
Literally just some typo in Cluster.js `<Label>` where should be fontUrl not labelFontUrl
```
[ ] Yes
[x] No
```
=> change labelFontUrl to fontUrl for cluster

src/GraphCanvas.tsx, src/themes/theme.ts
This adds the ability to make the canvas background transparent by not passing one in
```
[ ] Bugfix
[x] Feature
```
You couldn't get a transparent background on `GraphCanvas`
You can get a transparent background on `GraphCanvas` by excluding `canvas.background` from the `theme` object
```
[ ] Yes
[ ] No
```
=> Add transparent backgrounds

docs/Layouts.mdx, src/layout/hierarchical.ts
```
[ ] Bugfix
[x] Feature
```
In some cases, when using the Hierarchical 2D layout, nodes can overlap if the text is large and there is no easy way for the user to space out the nodes.
The user can space out the nodes by modifying the layout override nodeSeparation or increase the static size of each node using the nodeSize layout override of HierarchicalLayoutInputs. The new layout overrides are optionals and the default values are set to the …
=> Add overrides for node size to Hierarchical 2D

docs/assets/demo.ts, docs/demos/Cluster.story.tsx, src/layout/forceInABox.ts, src/utils/cluster.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/reaviz/reagraph/issues/160
Now we can make partial clusters even if clusterAttribute is not defined in some of the nodes. 
```
[ ] Yes
[x] No
```
=> Make partial clusters if clusterAttribute it not defined

src/layout/forceDirected.ts
```
[ ] Bugfix
[ ] Feature
```
Clusters start to overlap alot on larger datasets
Clusters overlap less on larger datasets
```
[ ] Yes
[x] No
```
This isn't a perfect fix. Some clusters are kinda far apart and there's still some overlap, but it's better than before
Before & after:
250 nodes
500 nodes
1000 nodes
=> Fix cluster overlap

src/CameraControls/useCenterGraph.ts, src/GraphScene.tsx, src/store.ts, src/useGraph.ts, src/utils/graph.ts, src/utils/visibility.ts
```
[ ] Bugfix
[x] Feature
```
Labels show on every node even when there so small they're unreadable. This can have a big impact on performance
Labels don't render when they're so small they can't be read. This is based off zoom and distance from camera
```
[ ] Yes
[x] No
```
BEFORE
https://github.com/reaviz/reagraph/assets/40581813/e2880203-ead6-4f21-accc-18c50e055a28
AFTER
https://github.com/reaviz/reagraph/assets/40581813/9de77a72-4602-41e2-85f1-997bf1769cce …
=> Hide labels based off distance from camera

src/layout/forceDirected.ts, src/layout/layoutProvider.ts
```
[ ] Bugfix
[ ] Feature
```
Better spacing on `forceDirected2d` graphs
```
[ ] Yes
[x] No
```
e.g. of 1000 nodes
BEFORE
AFTER
This also affected some medium sized graphs like below. The "before" debatably looks better here tho 😅 
BEFORE
AFTER
=> Adjust force directed 2d graph spacing

src/CameraControls/useCenterGraph.ts, src/CameraControls/utils.test.ts, src/CameraControls/utils.ts
```
[x] Bugfix
[ ] Feature
```
2d graphs over-rotate sometimes when selecting or de-selecting a node
Issue Number: #192 
2d graphs will rotate to the closest flat axis on node selection
```
[ ] Yes
[x] No
```
BEFORE
https://github.com/reaviz/reagraph/assets/40581813/d27e7a59-cbf0-4d09-b94a-274240732707
AFTER
https://github.com/reaviz/reagraph/assets/40581813/7f1710db-9f6f-49d3-bbf8-e9a97d44744d
=> Fix 2d graph over-rotating on node select

src/CameraControls/useCenterGraph.ts
```
[x] Bugfix
[ ] Feature
```
The camera re-orients on de-select even when it's not necessary - all nodes are in view
Issue Number: #194 
The camera doesn't re-orient when all nodes are in view
```
[ ] Yes
[x] No
```
BEFORE
https://github.com/reaviz/reagraph/assets/40581813/5ee72477-fec7-42a4-9294-cb8bd69fc284
AFTER
https://github.com/reaviz/reagraph/assets/40581813/da804423-9a0e-4703-be9a-a45810c85062
=> Fix camera reorient on deselect

src/symbols/Node.tsx
```
[x] Bugfix
[ ] Feature
```
Camera moves slightly after releasing a dragged node
Issue Number: #193 
Camera doesn't move after releasing a drag
```
[ ] Yes
[x] No
```
What seemed to be happening here is -> inside the drag function the camera controls get disabled, but the drag doesn't actually trigger until after you've started dragging your cursor a bit. This means the camera starts panning THEN the drag begins.
I think the camera moving on drag release is a …
=> Fix camera moving slightly on drag

src/symbols/Node.tsx
```
[x] Bugfix
[ ] Feature
```
You can't zoom the camera while hovering a node
You can zoom while hovering a node
```
[ ] Yes
[x] No
```
The camera controls were being entirely disabled while hovering a node. Set the truckSpeed to 0 instead ("Speed of drag for truck and pedestal")
=> Fix can't zoom while hovering a node

src/CameraControls/CameraControls.tsx
```
[x] Bugfix
[ ] Feature
```
The camera only zooms towards the center of the graph
Issue Number: #200 
When zooming with your mousewheel, the camera zooms towards the cursor 
```
[ ] Yes
[x] No
```
This switches mouse wheel behavior to dolly instead of zoom
This allows the `dollyToCursor` prop to do its thing
https://github.com/reaviz/reagraph/assets/40581813/582b58d2-5866-494b-8276-a83cad13f5c2
=> Fix zoom to cursor

src/CameraControls/useCenterGraph.ts
```
[x] Bugfix
[ ] Feature
```
When node positions change (from dragging, layout change, etc.) they can sometimes go outside the camera's view. Then the user has to pan the camera around to look for the graph
The camera re-centers on the graph when node positions change and any are out of view
```
[ ] Yes
[x] No
```
BEFORE
https://github.com/reaviz/reagraph/assets/40581813/e90f47a0-ca82-4b77-b6ba-e4670c434f52
https://github.com/reaviz/reagraph/assets/40581813/b2297b2a-f …
=> Re-center camera when nodes update

docs/Centering.mdx, docs/demos/Basic.story.tsx, src/CameraControls/useCenterGraph.ts
```
[x] Bugfix
[ ] Feature
```
The camera resets while zooming in on a big graph when label visibility switches
The camera also resets while dragging nodes when other nodes are out view. 
Issue Number: #213 #214 
The camera doesn't re-center automatically when nodes/labels update. Centering the camera is now left to be handled on a case-by-case basis using the `centerGraph` method from `GraphCanvasRef`
```
[ ] Yes
[x] No
```
The `node.labelVisible` field was triggering …
=> Fix camera view resetting on label visibility change

src/GraphScene.tsx, src/symbols/Cluster.tsx, src/symbols/Edge.tsx, src/symbols/Line.tsx, src/symbols/Node.tsx
This PR:
- adds events for Click and Pointer (hover) callback API for Nodes, Edges and Clusters (see discussion https://github.com/reaviz/reagraph/discussions/221)
- fixes some typos
Issues and inconsistencies I couldn't decide on my own:
- exposing ThreeEvent types feels like a bad smell to me. It cant be casted to vanilla event because it lacks some attributes. Also consider onCanvasClick has vanilla MouseEvent as an argument already. Solutions could be casting to intersection between ThreeEvent and vanilla event and/or reexporting ThreeEvents under new alias.
- because of edge intersection (see Edges.tsx) I could not make event argument non-optional for onEdge... events
- because of existing optional second argument for onNodeClick I had to make event argument also optional. I suggest …
=> Expose events for Click and Pointer API

src/symbols/Edge.tsx
```
[x] Bugfix
[ ] Feature
```
When opening the `context menu` on Edges (the ones used when animation is on), the menu is not centered on the Edge line
The context menu is centered on the Edge line
```
[ ] Yes
[x] No
```
=> Fix Edge context menu position

.eslintrc.cjs, package.json
[x] Bugfix
[x] Refactoring (no functional changes, no api changes)
[x] Build related changes
[x] CI related changes
eslint was not running properly in VSCode Windows. Missing target source directory in package.json was preventing linter from finding issues. After fixing that got warning about missing react version in eslint config. This is fixed in PR as well
Works fine for my setup (VS Code on Windows). If error is introduced 'npm run' lint correctly identifies it
No, but could affect build actions.
=> Fix eslint setup

package-lock.json, src/symbols/Edge.tsx, src/symbols/Label.tsx, src/symbols/edges/Edge.tsx
```
[x] Bugfix
[ ] Feature
```
the `GraphScene` prop `edgeLabelPosition` values `inline`, `below`, and `above` don't display the label parallel to the edge - they should
`edgeLabelPosition`'s behave as expected
```
[ ] Yes
[x] No
```
This is a regression that happened from commit 4c2d0b4c4dd62af4845faf7d0886a97cf33786f7
Not positive why that package upgrade caused it, but applying the label rotation to the underlying `<Text>` instead of the group fixes
BEFORE
AFTER
=> Fix label rotation

src/layout/forceDirected.ts
```
[x] Bugfix
[ ] Feature
```
Graphs sometimes fly to entirely different locations when switching the layout type
Different graph layouts stay centered on the same origin
```
[ ] Yes
[x] No
```
This centers all graph simulations on (0,0) so they don't fly across the view when you switch the layout
BEFORE
https://github.com/reaviz/reagraph/assets/40581813/79f71871-a9b2-4d27-8c75-8a6c57d82afe
AFTER
https://github.com/reaviz/reagraph/assets/40581813/594c6730-2c1d-48e2-bc0 …
=> Fix jerky layout switching

docs/Centering.mdx, docs/demos/Basic.story.tsx, docs/demos/Controls.story.tsx, src/CameraControls/useCenterGraph.ts, src/GraphCanvas.tsx, src/GraphScene.tsx, src/selection/useSelection.ts
```
[ ] Bugfix
[x] Feature
```
Centering the graph also adjusts the zoom
Issue Number: #130 
Centering the graph doesn't change the zoom. There's a new function `fitNodesInView` that replaces that functionality
```
[x] Yes - sort of
[ ] No
```
This takes the fit/zoom functionality out of the `centerGraph` function and puts it into a separate `fitNodesInView` function
This lets users have more control over centering behavior …
=> Add fit nodes in view func

src/CameraControls/useCenterGraph.ts
```
[x] Bugfix
[ ] Feature
```
If you pan and zoom, then fit nodes to the view, sometimes the view doesn't fit properly
The view always fits properly
```
[ ] Yes
[x] No
```
This awaits the zoom reset before positioning the camera when triggering `fitNodesInView`. Now there's a visual split between zooming and positioning the camera, but it's better than the view not being fit to the nodes properly
BEFORE
(happened on the 3rd fit to view trigger) …
=> Fix fit view bug after panning and zooming

.storybook/preview.tsx, package-lock.json, package.json, src/symbols/Cluster.tsx, src/symbols/Edge.tsx, src/symbols/Label.tsx, src/symbols/Node.tsx, src/symbols/Ring.tsx, src/symbols/edges/Edge.tsx, src/symbols/nodes/Svg.tsx
We hit issue when working with some other packages with react-three/drei(the new name of glodrei)
```
./node_modules/glodrei/core/useSpriteLoader.js
Attempted import error: 'sRGBEncoding' is not exported from 'three' (imported as 'THREE').
```
As above
Now it's back normal.
```
[ ] Yes
[x] No
```
=> bump glodrei to its successor react-three/drei

src/symbols/Node.tsx
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fixed labelType none still shows label when hovering over node

src/symbols/Edge.tsx, src/types.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> add fill property to edge and set the arrow and the line color by it

docs/Theme.mdx, src/symbols/Cluster.tsx, src/themes/theme.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> Add ability to customise Label font size and offset

docs/demos/Cluster.story.tsx, src/GraphScene.tsx, src/symbols/Node.tsx, src/types.ts, src/useGraph.ts, src/utils/cluster.ts, src/utils/graph.ts, src/utils/useDrag.ts
This PR:
- Constrains node dragging to cluster bounds
=> Constrain Nodes to Clusters

src/GraphScene.tsx, src/useGraph.ts
```
[x] Bugfix
[ ] Feature
```
Cluster position is not updating after node dragging
Cluster position is updating after node dragging
https://github.com/user-attachments/assets/b4225543-ec65-442c-9d1f-ac6497f13a1c
```
[ ] Yes
[x] No
```
=> Update cluster position after node dragging

src/selection/useSelection.ts
The aim of this PR is to fix issue #272 => Copy/Paste/Refresh keyboard shortcuts not working if using useSelection Hook
```
[X] Bugfix
[ ] Feature
```
Issue Number: #272
Copy paste is now working (you can try it for instance on the text 'Hold Cammand/CTRL ....') in the Modifier Key section.
```
[ ] Yes
[X] No
```
=> Fix to make Copy/Paste keyboard shortcuts working with useSelection

src/layout/circular2d.ts
One liner change to fix hard-coding of radius for CircularLayoutInputs
```
[x] Bugfix
[ ] Feature
```
You have to create your own interface for it that takes in a number and extends LayoutFactoryProps, but it would be nice to not have to duplicate these interfaces, since it's already defined with your library.
Switching hard-coded radius to use a type of number.
```
[ ] Yes
[x] No
```
Again, if this is designed intentionally this way - please let me …
=> bugfix: Fixing hardcoded radius

docs/demos/AggregateEdges.story.tsx, src/GraphCanvas/GraphCanvas.tsx, src/GraphScene.tsx, src/symbols/Label.tsx, src/symbols/Line.tsx, src/utils/aggregateEdges.ts, src/utils/position.ts
```
[ ] Bugfix
[x] Feature
```
Previously, edges used to stack on top of each other when there were more than three edges between two nodes.
Now, we can pass an optional `aggregateEdges` prop to aggregate edges that connect the same pair of nodes in both directions.
https://github.com/user-attachments/assets/daa23e30-6cf0-4d77-ad17-79e831e8c0dc
```
[ ] Yes
[x] No
```
=> Add Aggregate Edges Functionality

src/symbols/Edge.tsx, src/symbols/Line.tsx, src/types.ts, stories/demos/Edges.story.tsx
```
[ ] Bugfix
[x] Feature
```
* Normalized dash size to depend on the line length
* Add dashSize for better control if needed
```
[ ] Yes
[x] No
```
=> Add dashSize prop

src/GraphCanvas/GraphCanvas.tsx, stories/demos/Basic.story.tsx
```
[x] Bugfix
[ ] Feature
```
https://github.com/reaviz/reagraph/issues/217
https://github.com/user-attachments/assets/09aa27f8-425d-4f0d-837a-a72c4951fc71
```
[ ] Yes
[ ] No
```
=> Fix for the Min/Max distance #217

src/layout/concentric.ts, src/layout/concentric2d.ts, src/layout/concentric3d.ts, src/layout/layoutProvider.ts, src/layout/types.ts, stories/demos/ThreeLayouts.story.tsx
```
[ ] Bugfix
[x] Feature
```
Added new 3D concentric layout
```
[ ] Yes
[x] No
```
https://github.com/user-attachments/assets/340c7ca5-32ed-4934-a0fd-7a933a11725a
=> Concentric 3D

src/symbols/edges/Edge.tsx
```
[x] Bugfix
[ ] Feature
```
Edge label rotation is wrong when animated=false
Edge label rotation is correct when animated=false
```
[ ] Yes
[x] No
```
Before
After
=> Fix edge label rotation when animated=false

src/CameraControls/CameraControls.tsx, src/GraphCanvas/GraphCanvas.tsx, src/symbols/Edge.tsx, src/symbols/Line.tsx
```
[x] Bugfix
[x] Feature
```
GET-34 & GET-35
https://github.com/user-attachments/assets/ee794c4c-6354-461a-8913-6214c5186516
```
[ ] Yes
[x] No
```
=> Line Render order & orthographic camera min/max fixes
