reaviz/reagraph

docs/demos/Basic.story.tsx
src/helpers/useSelection.ts
src/layout/forceDirected.ts

Please check if your PR fulfils the following requirements:
- ~~[ ] Tests for the changes have been added (for bug fixes / features)~~ N/A
- ~~[ ] Docs have been added / updated (for bug fixes / features)~~ N/A
```
[ x ] Bugfix
[ ] Feature
```
Get message about it being unable to find the "types" module
Don't get a message about it being unable to find the "types" module
```
[ ] Yes
[x] No
```

Fix 2 `"types"` imports

---

docs/demos/Edges.story.tsx
src/GraphScene.tsx
src/symbols/Edge.tsx
src/utils/position.ts
src/utils/visibility.ts

```
[ ] Bugfix
[x] Feature
```
Labels were not aligned with the edge line
Issue Number: [21](https://github.com/reaviz/reagraph/issues/21)
Labels aligned with the edge line
```
[ ] Yes
[x] No
```

ISSUE-21: Edge Label Positions

---

src/GraphScene.tsx
src/symbols/Label.tsx
src/symbols/Node.tsx

chore: allow user pass custom font url for label display

---

src/CameraControls/CameraControls.tsx
src/CameraControls/useCameraControls.ts
src/GraphCanvas.tsx
src/GraphScene.tsx
src/symbols/Node.tsx
src/utils/useDrag.ts

```
[x] Bugfix
[ ] Feature
```
When canvas has some position offset - node jumping when drag start
```
[ ] Yes
[x] No
```
Had try to pass canvas container parameters with context, but it didn't work properly

ISSUE-42: Dragging Offset Bug

---

src/CameraControls/useCenterGraph.ts
src/selection/useSelection.ts
src/selection/utils.ts

```
[x] Bugfix
[ ] Feature
```
Selecting a node doesn't provide the best zooming and centering
Use cover property of fitToBox along with taking adjacent nodes into consideration when centering the camera
```
[ ] Yes
[x] No
```
https://user-images.githubusercontent.com/6655992/190878358-26e2fb59-a69e-4ee4-96aa-42b0d752a938.mov

take adjacent nodes into account of selection zoom

---

src/utils/collapse.ts

```
[x] Bugfix
[ ] Feature
```
Collapsing the root node will not hide nodes which have multiple incoming edges
Pass hidden nodes and edges properly
```
[ ] Yes
[x] No
```

fix hidden nodes when multiple incoming edges

---

src/collapse/useCollapse.ts

```
[x] Bugfix
[ ] Feature
```
getIsCollapsed returns true if the provided node is visible instead of if it is not visible
Negate return statement of getIsCollapsed to return true if node is not visible
```
[ ] Yes
[x] No
```

getIsCollapsed missing a not

---

src/symbols/Edge.tsx
src/symbols/Line.tsx
src/symbols/edges/Edge.tsx
src/symbols/edges/useEdgeGeometry.ts
src/utils/arrow.ts
src/utils/position.ts

Fixes #82 
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Fix edge ends and label rotation

---

src/symbols/edges/Edges.tsx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Don't intersect edges until scene is interacted with

---

src/symbols/Edge.tsx
src/symbols/edges/Edge.tsx

Fixes #85 
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Fix edge label positioning

---

docs/demos/MultiSelection.story.tsx
src/selection/Lasso.tsx
src/store.ts
src/symbols/Node.tsx
src/symbols/nodes/Sphere.tsx

Revert "Fix some drag bugs and enable dragging multiple nodes"

---

docs/demos/MultiSelection.story.tsx
src/selection/Lasso.tsx
src/store.ts
src/symbols/Node.tsx
src/symbols/nodes/Sphere.tsx

Revert "Revert "Fix some drag bugs and enable dragging multiple nodes""

---

src/store.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Small drag fixes

---

README.md

```
[] Bugfix
[ ] Feature
[x] Documentation content changes
```
```
[] Yes
[x] No
```

Fixed incorrect node IDs in readme usage example

---

docs/demos/Basic.story.tsx
src/symbols/Node.tsx
src/types.ts

Adding ability to show subLabel (literally just second line) for the `<Node/>`.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Add subLabel to <Node/>

---

src/layout/forceatlas2.ts
src/sizing/centrality.ts
src/sizing/pageRank.ts

Fix imports with webpack 5
https://github.com/reaviz/reagraph/issues/115
```
[x] Bugfix
[ ] Feature
```

Fix imports with webpack 5

---

src/store.ts
src/symbols/Edge.tsx
src/symbols/Line.tsx
src/symbols/edges/useEdgeGeometry.ts
src/utils/position.ts

```
[ ] Bugfix
[x] Feature
```
Edges coming from the same source and going to the same target (called parallel edges in graphology docs) aren't being rendered when multiple of them exist
Parallel edges are all displayed
```
[ ] Yes
[x] No
```
https://github.com/reaviz/reagraph/assets/40581813/059888ef-255f-4208-afa6-b539af14efc3

Add parallel edge graph support

---

src/CameraControls/useCenterGraph.ts
src/symbols/Arrow.tsx
src/symbols/Line.tsx
src/symbols/Node.tsx

```
[x] Bugfix
[ ] Feature
```
The animation on the enter of the chart is not centered.
The animation start from the center.
https://github.com/reaviz/reagraph/assets/11332713/404247b0-ca79-4240-9475-bc5756504228
```
[ ] Yes
[x] No
```

fix issue initial zoom off center

---

src/CameraControls/CameraControls.tsx
src/GraphCanvas.tsx
src/GraphScene.tsx

```
[x] Bugfix
[ ] Feature
```
The disabled storybook story doesn't  work and many storybook story doesn't work.
fixed disable behavior
https://github.com/reaviz/reagraph/assets/11332713/f7d32ce9-f36f-45cc-b000-7094366439c2
```
[ ] Yes
[x] No
```

fix issue with disabled parameter

---

src/GraphScene.tsx

```
[x] Bugfix
[ ] Feature
```
Sometimes not all disabled graphs are loaded.
Now all disabled graphs are loaded.
```
[ ] Yes
[x] No
```

fix issue with many disabled graphs

---

package-lock.json
package.json

fix: @react-three/drei package version update

---

src/GraphCanvas.tsx
src/GraphScene.tsx
src/selection/Lasso.tsx
src/symbols/Cluster.tsx
src/symbols/Edge.tsx
src/symbols/Node.tsx

```
[ ] Bugfix
[ ] Feature
```
Improved FPS and stuttering most noticeable on large datasets
```
[ ] Yes
[x] No
```
This is based off react-three-fiber's recommendations to not mount indiscriminately: https://docs.pmnd.rs/react-three-fiber/advanced/pitfalls#don't-mount-indiscriminately
BEFORE
https://github.com/reaviz/reagraph/assets/40581813/afb9dbfa-013e-4b08-8b64-51d7d71027a7
AFTER
https://github.com/reaviz/reagraph/assets/40581813/4641faaa-89f7-46d0-94d1 …

Improve performance

---

package-lock.json
src/CameraControls/useCenterGraph.ts

```
[ ] Bugfix
[ ] Feature
```
Graph's re-orient themselves on every selection - even when it's not necessary because all the nodes are already in view
Graph's re-orient and focus on all selected nodes only when they're not already in view
```
[ ] Yes
[x] No
```
Not a breaking change, but a notable change in behavior
BEFORE
https://github.com/reaviz/reagraph/assets/40581813/07f9612f-9a31-4522-9aba-5db6b2d9d55f …

Improve graph selection re-orientation

---

src/CameraControls/index.ts
src/CameraControls/useCenterGraph.ts
src/CameraControls/utils.ts
src/GraphScene.tsx
src/layout/layoutUtils.ts
src/symbols/Edge.tsx
src/useGraph.ts

Code wise these should help but i can't tell any difference honestly. @ghsteff

Performance Improvements

---

src/CameraControls/useCenterGraph.ts

```
[x] Bugfix
[ ] Feature
```
Sometimes the graph loads off centered
The graph always loads centered
```
[ ] Yes
[x] No
```
BEFORE
AFTER

Fix graph centering

---

src/utils/graph.ts

```
[x] Bugfix
[ ] Feature
```
When a graph has a node count over 20, nodes with a size less than 7 should have a hidden label, but they don't
^ this works
```
[ ] Yes
[x] No
```
BEFORE
AFTER
https://github.com/reaviz/reagraph/assets/40581813/a3cf80e1-0d8a-429d-8ed3-8171662130c9
https://github.com/reaviz/reagraph/assets/40581813/5a5617a8-25e3-41ed-b506-382dd6b3f16c

Fix node label visibility calculation

---

src/CameraControls/utils.ts

```
[ ] Bugfix
[ ] Feature
```
Graph's that have been zoomed on properly re-orient when selecting nodes outside the camera's view
```
[ ] Yes
[x] No
```
https://github.com/reaviz/reagraph/assets/40581813/5619cfbe-7c4e-4650-af2d-9b1867c56359

Adjust zoomed graph re-orientation

---

src/utils/visibility.ts

```
[ ] Bugfix
[x] Feature
```
Labels of small nodes are never visible in `labelType: auto` unless you hover the node
Labels of small nodes with `labelType: auto` are now visible when the camera gets close enough
```
[ ] Yes
[x] No
```
https://github.com/reaviz/reagraph/assets/40581813/800798b2-3f28-46fb-9d4e-2ff2e888bc55

Improve label visibility for small nodes

---

src/GraphScene.tsx
src/symbols/Node.tsx

This will fix a bug where Edges are rendered on top of Nodes, and Nodes become barely visible on heavily connected networks.
Details in https://github.com/reaviz/reagraph/issues/223
```
[x] Bugfix
[ ] Feature
```
Edges are rendered on top of Nodes, and Nodes become barely visible on heavily connected networks
Issue Number: [N/A](https://github.com/reaviz/reagraph/issues/223)
Render priority for Nodes is increased, so Nodes are always visible
```
[ ] Yes
[x] No
```

Node render order

---

docs/Theme.mdx

```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
A coma is missing in the value of the `lightTheme` variable, causing a TS error when copy-pasting it.
The inline object is now ok.
```
[ ] Yes
[x] No
```

Fix typo in the example of the Theme section

---

src/symbols/Node.tsx

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Remove active state from selection property

---

src/CameraControls/CameraControls.tsx

```
[x] Bugfix
[ ] Feature
```
If you drag the camera and then quickly drag a node, both actions happen simultaneously
You can't drag the camera and a node simultaneously
```
[ ] Yes
[x] No
```
BEFORE
https://github.com/reaviz/reagraph/assets/40581813/84db9d2d-c754-4309-a4e1-2928002ae431
AFTER
https://github.com/reaviz/reagraph/assets/40581813/c9da5781-1dc5-4a16-9774-645825ab9ed6

Fix camera pan while dragging node bug

---

package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
[Issue](https://github.com/webNeat/ctrl-keys/issues/8)
```
[ ] Yes
[x] No
```

Update reakeys dep

---

.storybook/preview.tsx
package-lock.json
package.json
src/symbols/Cluster.tsx
src/symbols/Edge.tsx
src/symbols/Label.tsx
src/symbols/Node.tsx
src/symbols/Ring.tsx
src/symbols/edges/Edge.tsx
src/symbols/nodes/Svg.tsx

Revert "bump glodrei to its successor react-three/drei"

---

src/CameraControls/CameraControls.tsx
src/store.ts
src/symbols/Arrow.tsx
src/symbols/Edge.tsx
src/symbols/Line.tsx
src/symbols/Node.tsx
src/symbols/edges/Edge.tsx
src/symbols/edges/Edges.tsx

This PR:
- Refactors dragging state to be able to have multiple items dragging at same time

Refactor Dragging State

---

src/CameraControls/CameraControls.tsx
src/GraphCanvas.tsx
src/GraphScene.tsx
src/RadialMenu/RadialMenu.tsx
src/symbols/Arrow.tsx
src/symbols/Cluster.tsx
src/symbols/Edge.tsx
src/symbols/Label.tsx
src/symbols/Line.tsx
src/symbols/Node.tsx
src/symbols/Ring.tsx
src/symbols/edges/Edge.tsx
src/symbols/edges/useEdgeAnimations.ts
src/symbols/edges/useEdgeEvents.ts
src/symbols/edges/useEdgeGeometry.ts
src/symbols/nodes/Icon.tsx
src/symbols/nodes/Sphere.tsx
src/symbols/nodes/SphereWithIcon.tsx
src/symbols/nodes/SphereWithSvg.tsx
src/symbols/nodes/Svg.tsx
src/useGraph.ts

This PR:
- Removes defaultProps for react 19
- Various performance optimizations

Performance Optimizations

---

src/GraphScene.tsx
src/symbols/Cluster.tsx

```
[ ] Bugfix
[x] Feature
```
Add onClusterDragged event to have ability get new nodes position after dragging cluster
```
[ ] Yes
[x] No
```

Add onClusterDragged event

---

docs/demos/Cluster.story.tsx
src/GraphScene.tsx
src/symbols/Cluster.tsx
src/symbols/clusters/Ring.tsx
src/symbols/clusters/index.ts
src/types.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

Add ability to define custom cluster

---

package-lock.json
package.json
src/store.ts

```
[ ] Bugfix
[ ] Feature
[x] Other... Dependency update
```
```
[ ] Yes
[x] No
```

[WIP] Upgrade zustand to v5.0.5

---

src/selection/useSelection.ts
src/utils/dom.ts
src/utils/index.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #283 
```
[ ] Yes
[x] No
```
https://github.com/user-attachments/assets/d1d3225c-6b92-415f-a28b-a41541cd89a8

[Fix] Can't deselect nodes in multiModifier mode

---

src/symbols/Edge.tsx
src/symbols/Line.tsx
src/types.ts
stories/demos/Edges.story.tsx

```
[ ] Bugfix
[x] Feature
```
Edge now supports an additional property that allows edges to appear as dashed lines
```
[ ] Yes
[x] No
```

Dashed Edge

---

src/symbols/Edge.tsx
src/symbols/edges/useEdgeGeometry.ts
src/types.ts
stories/demos/EdgeArrows.story.tsx
stories/demos/EdgeCurved.story.tsx

```
[ ] Bugfix
[x] Feature
```
Individual props allowing overrides of `<GraphCanvas />` props:
* add `arrowPlacement` prop to the Edge
* add `interpolation` prop to the Edge
```
[ ] Yes
[x] No
```

Individual Edge props (arrowPlacement & interpolation)

---

src/symbols/Edge.tsx
src/symbols/edges/SelfLoop.tsx
src/symbols/edges/useEdgeGeometry.ts
src/utils/position.test.ts
src/utils/position.ts
stories/demos/Basic.story.tsx

```
[x] Bugfix
[x] Feature
```
Circular Edges Not Working #16
When source === target creates self-loop 
```
[ ] Yes
[x] No
```

SelfLoop component

---

src/GraphCanvas/GraphCanvas.tsx

```
[x] Bugfix
[ ] Feature
```
Issue Number: 220
https://github.com/reaviz/reagraph/issues/220
before:
https://github.com/user-attachments/assets/b64f152b-54e3-48e3-9703-f26de6acd71d
after:
https://github.com/user-attachments/assets/b75ce916-ef72-471c-983b-d49bdf5d9fe5
```
[ ] Yes
[x] No
```

add useEffect to reset the store when theme is modified

---

src/store.ts
src/symbols/edges/Edges.tsx
src/symbols/edges/useEdgeEvents.ts
stories/demos/HoverHighlightTypes.story.tsx

```
[x] Bugfix
[ ] Feature
```
[#364](https://github.com/reaviz/reagraph/issues/364)
https://github.com/user-attachments/assets/2770f40e-3292-44bc-9179-9e59c73bcc81
https://github.com/user-attachments/assets/e3557daa-3dd3-4121-9175-b8f399593a03
```
[ ] Yes
[x] No
```

Fix for Hover/Active State on Edge #364

---

src/selection/Lasso.tsx
src/symbols/edges/useEdgeGeometry.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #210 
```
[ ] Yes
[x] No
```
https://github.com/user-attachments/assets/4b759459-bea3-4350-9bd1-ac4fea36bf41

Fix lasso selection for edges with disabled animation

---

stories/demos/Layouts.story.tsx

```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
```
[ ] Yes
[x] No
```
https://github.com/user-attachments/assets/48f68aa6-8288-416c-a64f-a97f5f4f1b42

Add sample with draggable custom layout

---

src/symbols/edges/useEdgeGeometry.ts
src/utils/geometry.ts
src/utils/index.ts
stories/demos/Edges.story.tsx

```
[x] Bugfix
[ ] Feature
```
No dash style when animation is disabled
Issue Number: #377 
Dash style works when animation disabled
```
[ ] Yes
[x] No
```

Add dash style for edges without animation
